default_stages: [commit]
exclude: ^third_party/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [-b, master, -b, develop]
    -   id: trailing-whitespace
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.4.4'
    hooks:
    -   id: ruff
        entry: bash -c 'echo $@ | xargs ruff check --force-exclude $RUFF_EXTRA_ARGS'
        args: [--this-arg-bizarrely-ignored, --fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        entry: bash -c 'echo $@ | xargs black $BLACK_EXTRA_ARGS' --
        language_version: python # Should be a command that runs python3.6+
